// Generated by CoffeeScript 1.3.1
var assert, fs, macho, path, _;

fs = require('fs');

path = require('path');

assert = require('assert');

_ = require('underscore');

macho = require('../liz');

describe('liz', function() {
  return it('should collect matching files on multiple levels', function() {
    var exampleDir, files, output;
    exampleDir = path.join(__dirname, 'example');
    output = path.join(exampleDir, 'templates.js');
    if (fs.existsSync(output)) {
      fs.unlinkSync(output);
    }
    files = liz.findMatching(exampleDir, '**/*.html');
    assert(_.contains(files, path.join(exampleDir, 'templates1.html')));
    return assert(_.contains(files, path.join(exampleDir, 'subfolder/moretemplates.html')));
  });
});
